apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: z0057393-staging
  namespace: coopink
spec:
  secretName: letsencrypt-staging-pub
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
  commonName: z0057393.com
  dnsNames:
    - z0057393.com
